### ISSUE TITLE
External Services support

### ISSUE THREAD

**Issue by ltabis** [viridIT/vSMTP#132]
**Is your feature request related to a problem? Please describe.**
vsmtp should be able to delegate workload using external services. (see #124 )

**Describe the solution you'd like**
vsmtp is able to communicate with those services via :
- unix shell (#119) 
- unix socket
- tcp sockets
- ldap/ad

**Declaring a service**
```toml
[service.mysrv1]

type = "shell"
user = "foo"
command = "foobar"
timeout = "10s"
args = "-c, -f /tmp/myfile, ${mail.full}" # rhai variables can be injected here
```

**Using a service**
```rust
rule preq "using_service" #{
  condition: || vsl.SERVICE("mysrv1").code == 0,
  ...
};
```

``vsl.SERVICE`` returns a special object for each type of service. (f.e. a service with `type = shell` returns the `Output` object)
