### ISSUE TITLE
Versioning of configuration

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#158]
The configuration should have a 'version_requirement' field to handle breaking changes on the format.

The following syntax should be supported (see https://semver.org) :

```toml
version_requirement = "^0.9.8"
version_requirement = ">=1.2.3, <1.8.0"
```
