### ISSUE TITLE
Next version of vSMTP configuration

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#186]
### Discussed in https://github.com/viridIT/vSMTP/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **Mathieu-Lala** March  9, 2022</sup>
Should the next version of the config looks like this ?

```toml
version_requirement = ">=0.10, <1.0.0"

[server]
domain = "testserver.com"
client_count_max = 16   

[server.system]
user = "vsmtp"
group = "vsmtp"

[server.system.thread_pool]
receiver = 6
processing = 6
delivery = 6

[server.interfaces]
addr = ["0.0.0.0:25", "[a:b:c:d::f]%nic:25", "[a:b:c:d:e::f]:25"]
addr_submission = ["127.0.0.1:587", "mta-01.localdomain:587"]
addr_submissions = ["10.0.4.254:465"]

[server.logs]
filepath = "/var/log/vsmtp/vsmtp.log"
format = "{d} {l} - "

[server.logs.level]
default = "warn"
receiver = "info"
rule_engine = "warn"
delivery = "error"


[server.queues]
dirpath = "/var/spool/vsmtp"

[server.queues.working]
channel_size = 32 

[server.queues.delivery]
channel_size = 32      
deferred_retry_max = 10
deferred_retry_period = "10s"
dead_file_lifetime = "14d"


[server.tls]
security_level = "May"
preempt_cipherlist = true
handshake_timeout = "100ms"
protocol_version = "^TLSv1.2"
certificate = "/etc/vsmtp/certs/certificate.crt"
private_key = "/etc/vsmtp/certs/privateKey.key"

[[server.tls.sni]]
domain = "testserver2.com"
certificate = "/etc/vsmtp/certs/testserver2/fullchain.{domain}.pem"
private_key = "/etc/vsmtp/certs/testserver2/rsa.{domain}.pem"

[[server.tls.sni]]
domain = "testserver3.com"
certificate = "/somewhere/fullchain.pem"
private_key = "/somewhere/mykey.pem"


[server.smtp]
rcpt_count_max = 25
disable_ehlo = false
required_extension = ["STARTTLS", "SMTPUTF8", "8BITMIME", "AUTH"]

[server.smtp.error]
soft_count = 5
hard_count = 10
delay = "5000ms"

[server.smtp.timeout_client]
connect = "50ms"
helo = "100ms"
mail_from = "200ms"
rcpt_to = "400ms"
data = "800ms"


[server.smtp.codes]
Help = "214 my custom help message\r\n"
Greetings = "220 {domain} ESMTP Service ready\r\n"


[server.smtp.startls]
# ???


[app]
dirpath = "/var/spool/vsmtp/app" 

[app.vsl]
filepath = "/etc/vsmtp/main.vsl"

[app.logs]
filepath = "/var/log/vsmtp/app.log"
level = "trace"
format = "{d} - {m}{n}"

[app.services.clamscan]
type = "shell"
timeout = "15s"
command = "/etc/vsmtp/service/clamscan.sh"
args = "{mail}"

[app.services.spamassassin]
type = "shell"
timeout = "15s"
command = "/etc/vsmtp/service/spamassassin.sh"
args = "{mail}"
user = "spamassassin"
group = "spamassassin"

```

**Comment by paguardiolle** [comment]
```toml
version_requirement = ">=0.10, <1.0.0"

[server]
domain = "testserver.com"           # must - to be changed to sthing like "my.fqdn.com"
client_count_max = 16               # opt - set to "16" 

[server.system]
user = "vsmtp"                      # must - ok
group = "vsmtp"                     # must - ok

[server.system.thread_pool]         # opt - set to 10 ?
receiver = 6                    
processing = 6
delivery = 6

[server.interfaces]
addr = ["0.0.0.0:25", "[a:b:c:d::f]%nic:25", "[a:b:c:d:e::f]:25"]       # must - set to [localhost:25]
addr_submission = ["127.0.0.1:587", "mta-01.localdomain:587"]           # opt - not set
addr_submissions = ["10.0.4.254:465"]                                   # opt - not set

[server.logs]                           
filepath = "/var/log/vsmtp/vsmtp.log"                                   # must - ok
format = "{d} {l} - "                                                   # opt - set to ? check w/ Lucas

[server.logs.level]
default = "warn"                                                        # opt - ok warn
receiver = "info"                                                       # opt - not set
rule_engine = "warn"                                                    # opt - not set
delivery = "error"                                                      # opt - not set


[server.queues]
dirpath = "/var/spool/vsmtp"                                            # must - ok

[server.queues.working]                                                 
channel_size = 32                                                       # opt - ok

[server.queues.delivery]
channel_size = 32                                                       # opt - ok
deferred_retry_max = 10                                                 # opt - set to ? RFC ? different behavior for Postfix (maximal_queue_lifetime = 5d)
deferred_retry_period = "10s"                                           # opt - set to ? RFC ? Postfix = 300s (minimal_backoff_time / queue_run_delay)
                                                                        #     Postfix double jusqu'à un maximal_backoff_time = 4000s ... until maximal_queue_lifetime
dead_file_lifetime = "14d"                                              # opt - infinite ?


[server.tls]
security_level = "May"                                                  # must - ok
preempt_cipherlist = true                                               # opt - ok
handshake_timeout = "100ms"                                             # opt - ?
protocol_version = "^TLSv1.2"                                           # opt - ok
certificate = "/etc/vsmtp/certs/certificate.crt"                        # opt - ok
private_key = "/etc/vsmtp/certs/privateKey.key"                         # opt - ok

[[server.tls.sni]]                                                      # opt - not set
domain = "testserver2.com"
certificate = "/etc/vsmtp/certs/testserver2/fullchain.{domain}.pem"     # <<<<<<<<<< WARNING remove domain
private_key = "/etc/vsmtp/certs/testserver2/rsa.{domain}.pem"           # <<<<<<<<<< WARNING remove domain

[[server.tls.sni]]                                                      # opt - not set
domain = "testserver3.com"
fullchain = "/somewhere/fullchain.pem"
private_key = "/somewhere/mykey.pem"


[server.smtp]                                                           
rcpt_count_max = 25                                                     # opt - postfix = 1000 ! smtpd_recipient_limit
disable_ehlo = false                                                    # opt - ok
required_extension = ["STARTTLS", "SMTPUTF8", "8BITMIME", "AUTH"]       # opt - ok

[server.smtp.error]                                                     
soft_count = 5                                                          # opt - postfix = 10
hard_count = 10                                                         # opt - postfix = 20
delay = "5000ms"                                                        # Postfix version 2.0 and earlier:
                                                                        # When the error count is less than $smtpd_soft_error_limit (default: 10) the Postfix smtpd(8) server delays all error replies by $smtpd_error_sleep_time (1 second with Postfix 2.0, 5 seconds with Postfix 1.1 and earlier).
                                                                        # When the error count reaches $smtpd_soft_error_limit, the Postfix smtpd(8) server delays all responses by "error count" seconds or $smtpd_error_sleep_time, whichever is more.
                                                                        # When the error count reaches $smtpd_hard_error_limit (default: 20) the Postfix smtpd(8) server breaks the connection.

[server.smtp.timeout_client]                                            # opt - RFC ?
Connect = "50ms"
Helo = "100ms"
MailFrom = "200ms"
RcptTo = "400ms"                                                        #
Data = "800ms"


[server.smtp.codes]                                                     # opt - not set - default ?        
Help = "214 my custom help message\r\n" 
Greetings = "220 {domain} ESMTP Service ready\r\n"


[server.smtp.startls]                                                   # Remove ?
# ???


[app]               
dirpath = "/var/spool/vsmtp/app"                                        # must - ok

[app.vsl]
filepath = "/etc/vsmtp/main.vsl"                                        # must - ok

[app.logs]
filepath = "/var/log/vsmtp/app.log"                                     # opt - ok
level = "trace"                                                         # opt - warn !!
format = "{d} - {m}{n}"                                                 # opt - ? format ?

[[app.services]]                                                        # opt 
name = "clamscan"
type = "shell"
timeout = "15s"
command = "/etc/vsmtp/service/clamscan.sh"
args = "{mail}"

[[app.services]]
name = "spamassassin"
type = "shell"
timeout = "15s"
command = "/etc/vsmtp/service/spamassassin.sh"
args = "{mail}"
user = "spamassassin"
group = "spamassassin"
```
