### ISSUE TITLE
Bump crate versions

### ISSUE THREAD

**Issue by ltabis** [viridIT/vSMTP#193]
Remove all crate minor version number in all cargo.toml.

```toml
# change this
regex = "1.5.4"
# to this
regex = "1.5"
```
