### ISSUE TITLE
ESMTP: Auth rfc 4954

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#39]
vSMTP will implement AUTH extension  see rfc : https://datatracker.ietf.org/doc/html/rfc4954

* add AUTH EHLO keyword contains as a parameter a space-separated list of the names of available SASL mechanisms
  * [x] PLAIN
  * [x] TLS
* add AUTH smtp verb : syntax = "AUTH mechanism [initial-response]"
  * [x] after a successful AUTH command completes, a server MUST reject any further AUTH commands with a 503 reply.
  * [x] An AUTH command issued during a mail transaction MUST be rejected with a 503 reply.
* [ ]  handle security layer negociation
* [ ]  when a security layer takes effect, the SMTP protocol is reset to the initial state
* MAIL FROM command
  * [ ] extend the line length of the MAIL FROM command by 500 characters
  * [x] add optional argument AUTH=mailbox : see rfc4954#section-5
  * [ ] ...
* [ ] when both TLS and SASL security layers are in effect, the TLS encoding MUST be applied after the SASL encoding
* [x] Status Codes : see rfc4954#section-6
* [ ] Insert the "Received:" header field at the beginning of the message content.
* mechanism (supported by rsasl)
  * [ ] ANONYMOUS
  * [ ] EXTERNAL
  * [x] LOGIN
  * [x] PLAIN
  * [ ] SECURID
  * [ ] DIGEST-MD5
  * [x] CRAM-MD5
  * [ ] SCRAM-SHA-1
  * [ ] SCRAM-SHA-1-PLUS
  * [ ] SCRAM-SHA-256
  * [ ] SCRAM-SHA-256-PLUS
  * [ ] SAML20
  * [ ] OPENID20
  * [ ] GSSAPI
  * [ ] GS2-KRB5
* [ ] improve config builder to generate ehlo message (auth mechanism & esmtp extension)
* [ ] test with auth under tls
* [ ] integrate authentication with the rule engine / config
* [ ] client side
* [x]  Configuration should add these options :
```toml
[server.smtp.auth]
must_be_authenticated = false # mail transaction will fail if not authenticated previously
enable_dangerous_mechanism_in_clair = false # allow clair mechanism on clair connection (should be true only if you want clair password on your network)
mechanisms = ["PLAIN", "LOGIN", "..."] # see the list above
attempt_count_max = -1 # number of AUTH command canceled allowed
```

This list is not exhaustive and will be updated over time.
