### ISSUE TITLE
Definition of what addr means is lacking

### ISSUE THREAD

**Issue by drahnr** [viridIT/vSMTP#393]
**Describe the bug**
In the book the basic configuration is rather minimal, it doesn't go through every line and explains the meaning. I am no smtp or email expert, and hence I personally would appreciate some more detail.

**Comment by Mathieu-Lala** [comment]
Yes indeed, I will had the links to docs.rs soon.

If you are talking about these field :
```toml
[server.interfaces]
addr = ["192.168.1.254:25"]
addr_submission = ["192.168.1.254:587"]
addr_submissions = ["192.168.1.254:465"]
```

Here is a quick explanation.
The SMTP protocol has changed over time, and several role has been defined for the servers :
MSA (Mail Submission Agent) : is responsible for the incoming traffic in the mail system ; listening on port 587 and 465 with TLS,  in the same fashion than HTTP over port 80 and HTTPS over 443. On these ports, stronger policies apply and client side authentication (SASL) is required.
MTA (Mail Transfer Agent) : is responsible to deliver the mails to the recipients's mail exchange, using the DNS logics ; listening on port 25, and using server side authentication (SPF / DKIM / DMARC ...).

So :
```toml
[server.interfaces]
addr = ["192.168.1.254:25"]    // <---- MTA's address
addr_submission = ["192.168.1.254:587"]     // <---- MSA's address
addr_submissions = ["192.168.1.254:465"]   // <---- MSA's address for SMTPS
```

These field are arrays, and you can leave any of them empty.

Thanks for your feedback
