### ISSUE TITLE
`syslog` support

### ISSUE THREAD

**Issue by Mathieu-Lala** [viridIT/vSMTP#474]
vSMTP will support logging to standard operating system.

`syslog` and `tracing_journald` can be used for that.

In some context, you might not want to have these feature enabled.
Should I wrap them under `--features syslog` and `--features journald` ?

**Comment by paguardiolle** [comment]
Imho syslog behavior must be included in the vsmtp.toml file. Do not forget that vSMTP is a daemon and not a "command line" application.

Syslog requires:
> On | Off
> Level
> Format
> Socket (done ?)
> Category "mail" hardcoded (done)

... and the corresponding vBook chapter must be rewrite.

**Comment by Mathieu-Lala** [comment]
```toml
[server.syslog] // if the table is not specified, syslog is disabled
min_level = "info"
format = "3164" | "5424"
unix = "/dev/log"
// or
tcp = "127.0.0.1:601"
// or
udp = "127.0.0.1:514"
```
