### ISSUE TITLE
Deferred Queue

### ISSUE THREAD

**Issue by ltabis** [viridIT/vSMTP#56]
The **Deferred Queue** is a vsmtp directory where message that couldn't be sent are stored.
It is is placed in the ``{smtp.spool_dir}/deferred``  directory.

An email is stored in the Deferred Queue when one of the following error happens:
- Invalid recipient address detected
- Email greylisted by spam filters
- Recipient server errors detected

**Configuration**
The deferred queue can be configured using the following arguments:
- `size`: the maximum size of the queue in memory. (the file system folder can contain as much emails as the system can store)
- `action`: can be `resend` or `delete`, resend or delete emails on startup.
- `cron`: cron job that executes `action` every x minutes. can be a number followed by `s` for seconds, `m` for minutes, `h` for hours, `d` for days. if not specified, the `action` is executed on every startup and when the deferred queue is full.
- `max_lifetime`: the time that the queue can try to send a specific email. At the end of this time, the email is moved into the **Dead Queue**. Can be a number followed by `s` for seconds, `m` for minutes, `h` for hours, `d` for days. default: `15d`.
example:

example:

```toml
# resend every emails from the deferred queue every 20 minutes.
# the queue in memory can only contain 100 mails at a time.
# if a mail cannot be send after one day, it is moved into the **Dead Queue**.
[deferred]
size = 100
action = "resend"
cron = "20m"
max_lifetime="1d"
```

**Alternative**
An external tool / binary could be used to interact with the deferred queue instead of the toml configuration.
A Rhai script could also be used.

```
receiver =>
  delivry ? log :
      dereferd ? log :
          dead => 10 days and retry
```

**Definitions of done**
- [x] the queue is created at ``{smtp.spool_dir}/deferred`` at startup if it doesn't already exists.
- [ ] the deferred queue can have a maximum size.
- [ ] the deferred queue need to be emptied following the toml config
  - [x] by sending all emails
  - [ ] by deleting all emails
  - [x] using a cron job
- [ ] if a message cannot be sent after again `max_lifetime`, it is moved to the dead queue.

**To consider**
Messages removed from the deferred queue after a failed `resend` action could be placed in a **Dead Queue**.
